export const coin_networks = {
    "Algorand": "ALGO",
    "Arbitrum One": "ARB",
    "Avalanche": "AVAX",
    "Base": "BASE",
    "Bitcoin": "BTC",
    "Binance Smart Chain (BSC)": "BNB",
    "Celo": "CELO",
    "Cronos": "CRO",
    "Dogecoin": "DOGE",
    "Ethereum": "ETH",
    "Fantom": "FTM",
    "Flare": "FLR",
    "Flow": "FLOW",
    "Harmony": "ONE",
    "Klaytn": "KLAYTN",
    "Kucoin": "KCS",
    "Litecoin": "LTC",
    "MultiversX (Elrond)": "EGLD",
    "Optimism": "OP",
    "Polygon": "MATIC",
    "Ripple (XRP)": "XRP",
    "Solana": "SOL",
    "Stellar": "XLM",
    "Tron": "TRX",
    "VeChain": "VET",
    "Xinfin": "XDC",
};

export const coin_networks_api = {
    "Algorand": "algorand",
    "Arbitrum One": "arb",
    "Avalanche": "avalanche",
    "Base": "base",
    "Bitcoin": "bitcoin",
    "Binance Smart Chain (BSC)": "bsc",
    "Celo": "celo",
    "Cronos": "cronos",
    "Dogecoin": "dogecoin",
    "Ethereum": "ethereum",
    "Fantom": "fantom",
    "Flare": "flare",
    "Flow": "flow",
    "Harmony": "one",
    "Klaytn": "klaytn",
    "Kucoin": "kcs",
    "Litecoin": "litecoin",
    "MultiversX (Elrond)": "egld",
    "Optimism": "optimism",
    "Polygon": "polygon",
    "Ripple (XRP)": "xrp",
    "Solana": "solana",
    "Stellar": "xlm",
    "Tron": "tron",
    "VeChain": "vet",
    "Xinfin": "xdc",
};